[upstream]
repo = "https://github.com/gominimal/pkgs"
branch = "main"
locked_commit = "616a592b93d2f635ef2b3cdb482f2b608fc4f9c5"

[tasks.echo]
packages = ["base"]
exec = ["echo", "hello from minimal"]
